### ISSUE TITLE
"Assertion `!"handleErrorPolicy error."' failed" on Fedora 21

### ISSUE THREAD

**Issue by nobrakal** [oxygine/oxygine-framework#10]
Hi,

I tried to run the HelloWorld example, and I got this: 
/home/$USER/oxygine-framework/oxygine/src/core/oxygine.cpp:919: void oxygine::handleErrorPolicy(oxygine::error_policy, const char*, ...): Assertion `!"handleErrorPolicy error."' failed.

However, oxygine and HelloWorld build sucessfully with cmake on my Fedora 21.

**Comment by frankinshtein** [comment]
Did you copy resources from HelloWorld/data folder to the folder with executable?
see oxygine-framework/readme/CMake.txt - #3

**Comment by nobrakal** [comment]
It works now! I'm an idiot, sorry. 
But, can you add this readme in the examples/HelloWorld/proj.cmake/COMPILE.txt, or something similar? Or add a command wich copy files from ../data in the right directory? I believe the cmake "add_custom_command " can do it...

Thank you for your (quick) help :)
