### ISSUE TITLE
No directory s3e directory on Github

### ISSUE THREAD

**Issue by JakubSzczerbinski** [oxygine/oxygine-framework#11]
Directory oxygine/src/core/s3e/ is missing on Github (https://github.com/oxygine/oxygine-framework/tree/master/oxygine/src/core) compared to Bitbucket (https://bitbucket.org/oxygine/oxygine-framework/src/032ffab81168f5457db9657b97039c00d5a5df08/oxygine/src/core).

**Comment by frankinshtein** [comment]
fixed
