### ISSUE TITLE
Is it possible to add tint?

### ISSUE THREAD

**Issue by sdelaysam** [oxygine/oxygine-framework#114]
Hi, @frankinshtein 

Is there a way to tint a sprite with color?
I've tried `VStyleActor::setColor` - it works but colors are blended.
What I want to achieve is to save source texture alpha and apply tint colour over it without blending colors.

**Comment by frankinshtein** [comment]
yes, there is examples/Demo/User Shader.
But I recommend you to switch oxygine to other branch: "ox-move", it has significantly improved rendrering system and other fixes

**Comment by sdelaysam** [comment]
Ok, thanks, will switch.
Btw, can tint be achieved with `normal` blend mode? 
_Using shader for that seems to be overkill_

**Comment by frankinshtein** [comment]
yes, it can be achieved.
_each sprite is rendering with shader._

**Comment by sdelaysam** [comment]
Sure, I mean its overkill for me as a user of framework to write a shader for a simple tint. Would be nice if framework provide it out-of-box. 
Especially, when you already have `VStyleActor::setColor` and it does tint, but with blending.
Can you add a `normal` blend mode or give a clue how to add it?

**Comment by frankinshtein** [comment]
implemented in "ox-move" branch, will be moved to "default" soon
