### ISSUE TITLE
File is saved to a different directory

### ISSUE THREAD

**Issue by DEXIT33** [oxygine/oxygine-framework#119]
I am not sure if I am just missing something, but when I open a file, modify it and save it back it is saved into the data-ram folder instead of the standard working directory. 

Also when I create new file using write function I cannot read it back again after relaunching the game, because it reads data from the working directory but file was save into the data-ram folder. How can I solve this?

**Comment by frankinshtein** [comment]
1. all modern applications should work this way. "Data" folder is always read only. On iOS/Android etc.
But if you want to ignore this then try:
file::wfs().setPath (file::fs().getFullPath(""));

2. you are wrong. Files reads from data-ram first, then if missing reads from data.

**Comment by DEXIT33** [comment]
I realized that it was problem on my side. I didn`t know that oxygine reads from data-ram first. Anyway, thank you for the explanation.
