### ISSUE TITLE
Bad project structure

### ISSUE THREAD

**Issue by xahon** [oxygine/oxygine-framework#120]
Cmake project requires to run `run.sh` to start. It changes directory to `data` and runs binary from it. How to debug? I'm using clion and it is cmake-based. It compiles cmake on-fly and i'm unable to run project. If i open clion in `proj.cmake` (And change root to `../` upper directory) it fails with `SIGSEGV` because inner function cannot find `res.xml`. I think you should change structure to cocos2dx-like. It contains root CMakeLists.txt that is compile and run ready. Building android, ios is not so often and can be done manually from time to time. But PC build is more and more often. The only one solution IMHO is to copy everything from `data` into `proj.cmake` and run. I'm gonna check it now

Can we discuss it?

Sorry for beginner english skill

**Comment by frankinshtein** [comment]
run.sh is just example for easy test and start out of box.
you could reorganize your own project like you want

**Comment by xahon** [comment]
@frankinshtein the problem is that clion sets project directory with absolute paths. Another programmer should configure it himself. If `gameResources.loadXML` could work with relative paths like `../data/res.xml` it would be very good

**Comment by frankinshtein** [comment]
https://youtu.be/dTtZEAfh_LM?t=261
