### ISSUE TITLE
What benefits of CLOSURE

### ISSUE THREAD

**Issue by xahon** [oxygine/oxygine-framework#122]
Why don't just use `std::bind`? 
`CLOSURE` macro always marked as error in CLion
![macro](https://user-images.githubusercontent.com/18731681/38201550-0ee857aa-36dc-11e8-887f-aa37ea70b98e.png)
I tried to find reason but there was a lot of templated and obfucsated sources

Replacing it with `std::bind` works fine
![image](https://user-images.githubusercontent.com/18731681/38201600-38b8a080-36dc-11e8-8464-cd0a017060e8.png)
And without errors

**Comment by frankinshtein** [comment]
1. it is faster
2. compatibility for older compilers without  C++11 support

**Comment by frankinshtein** [comment]
4. actor->removeEventListeners(this) - WON'T work, very useful feature
