### ISSUE TITLE
Examples are broken on Linux

### ISSUE THREAD

**Issue by shadwstalkr** [oxygine/oxygine-framework#13]
The buttons don't react to mouse events in the examples on Linux as of patch b39b96fbc81afbf14b18760bc18930d4aa24e174 .

**Comment by frankinshtein** [comment]
hm, I can't reproduce it
do you have multi touch device?

try to comment this lines (oxygine.cpp):

if (SDL_GetNumTouchDevices() > 0)
                _useTouchAPI = true;

**Comment by shadwstalkr** [comment]
Yeah, my laptop has multi touch. Commenting that out fixed it.

**Comment by frankinshtein** [comment]
fixed
