### ISSUE TITLE
cannot build with debug info

### ISSUE THREAD

**Issue by ambushed** [oxygine/oxygine-framework#130]
I am building HelloWorld example with --CMAKE_BUILD_TYPE=Debug in order to step through the code in gdb/cgdb.  However, all i get when i set a breakpoint at mainloop and run is assembly output.  

I am also trying _obj_dump_ to see if there is debug info with the same result.

Could you please advice?

Thanks

Vlad

**Comment by frankinshtein** [comment]
maybe
 -DCMAKE_BUILD_TYPE=DEBUG
