### ISSUE TITLE
Touch events slightly offset from sprite

### ISSUE THREAD

**Issue by Qbz23** [oxygine/oxygine-framework#133]
It seems to me touch events are slightly offset down and to the right from the actual sprite position. That is, in the upper left of the sprite, oxygine is not recognizing that my mouse is over the sprite. Similarly, if my mouse is nearby the sprite's bottom right but not actually on the sprite oxygine incorrectly recognizes that as being over the sprite. 

I hacked in a quick color tint on mouseover to illustrate the problem in the following video: 
[https://vimeo.com/277803674](https://vimeo.com/277803674)

**Comment by frankinshtein** [comment]
Don't know whats wrong with your sprite.
Open Examples/Demo - Alpha Hit Test
try to replace it with your sprite

**Comment by Qbz23** [comment]
I see no issue swapping in my sprite for alpha hit test. However, I notice that if I remove my resize in my game, it's perfectly correct. Is there something I need to call after resizing the sprite to properly match its hit box to its new size? The touch events are connected after the sprite resize.

**Comment by Qbz23** [comment]
sprite->setSize() after calling setResAnim

**Comment by frankinshtein** [comment]
thank you. fixed 
https://github.com/oxygine/oxygine-framework/commit/74b7d7320158d4f2596ded7ad3fca4d508169458
