### ISSUE TITLE
Input Text Demo not Rendering

### ISSUE THREAD

**Issue by cxsquared** [oxygine/oxygine-framework#15]
The text on the input text demo isn't rendering. I noticed the text is getting captured and set but it's not rendering correctly for some reason. I'm trying to figure out the problem but I've only started to use oxygine and only have a basic knowledge of C++ so I don't know how quick I'll figure it out.

**Comment by frankinshtein** [comment]
What OS? Compiler? Where you get Oxygine? Have you tried to update it latest?

**Comment by cxsquared** [comment]
My OS is OS X 10.10.5. I got Oxygine from the Oxygine website using the google drive link. I haven't tried the latest update. But the web demo on the Oxygine website doesn't show the text for me. It shows the click me but after I click the text doesn't update. I'm on Chrome for that.

**Comment by frankinshtein** [comment]
website could have outdated version.
Do you have any problems with build compiled by yourself?

**Comment by cxsquared** [comment]
I fixed my issue. It was a stupid mistake where I forgot to add the text as a child. But the website still has this issue which I guess is still a problem.
