### ISSUE TITLE
Forum is unavailable

### ISSUE THREAD

**Issue by kolombet** [oxygine/oxygine-framework#167]
I am using oxygine and happy with it. It's an amazing opensource project and I want it to be the flash successor. I want it to succeed and prosper.

I proposed to use oxygine instead of starling for the development of 2d mobile games to my friend. He told me that for him it seems dangerous to use it because oxygine forum is dead. Because of it, the project looks abandoned.

Can we support the project somehow to make the forum running again? It was a useful source of information for novices. I am ready to provide support for the project (server hosting/setup/donations).

**Comment by frankinshtein** [comment]
thank you. I fixed forum
