### ISSUE TITLE
Text on buttons disappearing sometimes.

### ISSUE THREAD

**Issue by jsaak** [oxygine/oxygine-framework#64]
On the demo website http://oxygine.org/online_demo.php
When i start Demo (the second one), then i select Performance, and then push Animate button several times, the text will disappear. I have seen multiple places with empty green buttons, i think there should be text on most of them.
(Linux 64bit / Chrome Version 49.0.2623.110 (64-bit))

**Comment by frankinshtein** [comment]
it is outdated
could you build demo and reproduce it yourself?

**Comment by jsaak** [comment]
I will try.

**Comment by jsaak** [comment]
I could reproduce with latest stable on linux using SDL.

There were some problems, sdl 2.0.0 is not enough had to upgrade to 2.0.4. (maybe 2.0.1 is enough?)
Had to convert run.sh to linux newlines. ($ unixtodos run.sh)
Had to chmod run.sh. ($ chmod 755 run.sh)

On a sidenote, i havent found the build scripts for emacsen, how to build those?

**Comment by frankinshtein** [comment]
oxygine uses latest SDL

**Comment by frankinshtein** [comment]
oh, I see. it is not bug 
text is dissapearing only on "animate" button
this is way how button animate works (check TestPerf.h)
