### ISSUE TITLE
Is there physic engine in the framework?

### ISSUE THREAD

**Issue by eray-z** [oxygine/oxygine-framework#65]
Hi, I can't see any document about physic engine with oxygine2d. I can't tutorial about physic object and collider..vs tutorials.

**Comment by frankinshtein** [comment]
examples/DemoBox2D

**Comment by eray-z** [comment]
It's great. Well, I'm working on my level editor project for a long time. 

https://www.facebook.com/turquoise2D

it's supporting cocos2d-x for now. But I want to add another frameworks. Maybe I can also add  oxygine2d soon. Can you help me for that in the future? Thanks.

**Comment by frankinshtein** [comment]
ok
