### ISSUE TITLE
Emscripten build uses SDL version 1, but why?

### ISSUE THREAD

**Issue by jsaak** [oxygine/oxygine-framework#67]
Unless you specify "-s USE_SDL=2" it uses SDL version 1.
When i pass USE_SDL=2 then input is not working (keyboard, touch).

I wanted to include SDL_net, that is why i am asking. I am not sure that using SDL 1 is the way.

**Comment by frankinshtein** [comment]
I recently updated oxygine to SDL2, check "emsc" branch.

**Comment by frankinshtein** [comment]
btw, only HelloWorld and Demo updated to SDL2

**Comment by ProgrammingLife** [comment]
Which changes should we do in our current projects to successfully work with next versions of oxygine?

**Comment by frankinshtein** [comment]
https://github.com/oxygine/oxygine-framework/commit/aa8e8b7b9a5b397c267024203d518834ce8c29a9
