### ISSUE TITLE
HTTP Request segmentation faults on Demo example

### ISSUE THREAD

**Issue by Aargonian** [oxygine/oxygine-framework#77]
Just poking around and trying Oxygine to see if it will work for a game I've been wanting to make. While poking around on the Demo project, the application crashed whenever the HTTP Request option was selected. The error given in my terminal upon crash was:

> error: Assert! _ptr && _ptr->_ref_counter > 0 in /home/aargonian/Development/Languages/C++/Cloned/oxygine-framework/oxygine/src/core/intrusive_ptr.h:42

I'm running on Ubuntu 16.04. GCC/G++ Version 5.4.0, Kernel 4.4.0 and I was compiling using the proj.cmake method and the run.sh shell script. Let me know if I can provide any additional information.

**Comment by Taymindis** [comment]
Is this Fixed? I having crash running DEMO

**Comment by frankinshtein** [comment]
fixed
