### ISSUE TITLE
Does Oxygine have support with mobile web?

### ISSUE THREAD

**Issue by spark-tw** [oxygine/oxygine-framework#78]
I run build_emsc.bat inside example/xxx/proj.cmake and generate xxx.js & xxx.html.

And I check xxx.js. There is no touch_start event. So, mobile web isn't supported?

All buttons of demo can't be triggered on Chrome for Android or Firefox on Android.

Thanks.

**Comment by frankinshtein** [comment]
I just tested Demos from http://oxygine.org/ on Android and it works
