### ISSUE TITLE
Compilation under Linux should use pkg-config

### ISSUE THREAD

**Issue by laerne** [oxygine/oxygine-framework#8]
Compilation under Linux should ideally use [pkg-config](http://www.freedesktop.org/wiki/Software/pkg-config/) to find include directories and compiler options.
CMake 2.6 provides a script with a function, [pkg_search_module](http://www.cmake.org/cmake/help/cmake2.6docs.html#module:FindPkgConfig), to interface easily with pkg-config.

For instance, I'm under fedora and compilation fails, simply because in fedora, they bundled SDL2 and SDL2main in one archive file, thus only "-lSDL2" should be passed to the compiler and passing "-lsdl2main" provokes an error.  Besides they use capital letters.

    % pkg-config sdl2 --libs
    -lSDL2 -lpthread 

I'm investigating on how to fix it.

**Comment by rtzoeller** [comment]
Any progress made on this issue? It still is a problem in Fedora 23.
