### ISSUE TITLE
HttpRequestTask segment fault on Example Demo, execute run from proj.cmake folder

### ISSUE THREAD

**Issue by Taymindis** [oxygine/oxygine-framework#85]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
build settings 
initialize oxygine
SDL build
creating window 960 640
display size: 960 640
ZipFS, total files: 13
oxygine initialized
DebugActor::initialize
ZipFS, total files: 13

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000053cbab in oxygine::HttpRequestTask::create() ()
#2  0x00000000005548ec in oxygine::WebImage::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#3  0x000000000052819b in Test::init() ()
#4  0x00000000004f94ae in example_init() ()
#5  0x0000000000527d8e in run() ()
#6  0x0000000000527e27 in main ()

**Comment by frankinshtein** [comment]
fixed
