### ISSUE TITLE
No emscripten example?

### ISSUE THREAD

**Issue by SavedByZero** [oxygine/oxygine-framework#91]
I'm mainly interested in html5 as a target.  I don't see any emscripten example in the sample projects, as the wiki says should be there.

**Comment by lukaszml** [comment]
Go to oxygine-framework -> examples -> Demo -> proj.cmake <- emscripten building files is here

**Comment by SavedByZero** [comment]
Thanks.

**Comment by frankinshtein** [comment]
https://github.com/oxygine/oxygine-framework/blob/master/readme/emscripten.txt
